Repository kawalcovid19/wargabantuwarga.com, pull requests merged in 2021-07, with the labels that each got.

#36 Install Google Tag Manager
  components/Script.tsx
  components/request-idle-callback.ts
  pages/index.tsx
Labels: enhancement

#47 Update Config “general”
  config.json
Labels: netlify-cms/pending_publish

#48 Create Sections “hubungi-hotline-wargabantuwarga”
  _content/sections/hubungi-hotline-wargabantuwarga.md
Labels: netlify-cms/pending_publish

#54 Create Section “informasi-terbaru”
  _content/sections/informasi-terbaru.md
Labels: netlify-cms/pending_publish

#58 Update Home Page “home_page”
  _content/home-page.yml
Labels: netlify-cms/pending_publish

#59 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#46 Experiment managing a page using Netlify CMS
  _content/home-page.md
  components/layout.js
  config.json
  env.d.ts
  lib/config.ts
  netlify.toml
  next.config.js
  package.json
  pages/home-page.tsx
  pages/index.tsx
  public/admin/config.yml
  public/admin/index.html
  yarn.lock
Labels: enhancement, help wanted

#19 Various optimizations
  .github/workflows/deploy.yml
  .prettierrc
  .prettierrc.json
  env.d.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/_document.tsx
  public/vercel.svg
  tsconfig.json
  yarn.lock
Labels: enhancement

#146 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#166 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#167 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#170 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#194 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#281 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#282 Update Config “general”
  config.json
Labels: netlify-cms/pending_publish

#295 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#300 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#301 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#302 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#303 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#307 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#311 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#312 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#316 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#331 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#349 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#355 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#369 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#370 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#371 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#373 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#390 Add home image banner field to Netlify CMS
  components/__tests__/search-form.test.tsx
  components/home/__tests__/homepage-header.test.tsx
  components/home/homepage-header.tsx
  components/ui/button/primary-button.tsx
  env.d.ts
  pages/index.tsx
  public/admin/config.yml
Labels: dx, enhancement

#407 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#408 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#409 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#306 feat: try lh ci to replace Netlify Plugin
  .github/workflows/lighthouse-ci.yml
  lighthouserc.js
  netlify.toml
Labels: need-perf-check

#415 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#418 fix: label checking
  .github/workflows/lighthouse-ci.yml
Labels: poc

#423 revert: bring back gtm
  pages/_app.tsx
  pages/home-page.tsx
Labels: need-perf-check

#435 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#436 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#438 fix(gtm): move noscript under body
  pages/_app.tsx
  pages/_document.tsx
Labels: need-perf-check

#441 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#442 Update Welcome Message “welcome_message”
  _content/welcome-message.json
Labels: netlify-cms/pending_publish

#446 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#451 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#462 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#465 Update Welcome Message “welcome_message”
  _content/welcome-message.md
Labels: netlify-cms/pending_publish

#466 Update Welcome Message “welcome_message”
  _content/welcome-message.md
Labels: netlify-cms/pending_publish

#471 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#475 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#476 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#478 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#485 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#489 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#490 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#491 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#488 Update Isoman Page “isoman_page”
  _content/isoman-page.json
Labels: netlify-cms/pending_publish

#494 fix: fix `isolasi-mandiri` page breadcrumb + add to menu
  __tests__/pages/faq.test.tsx
  __tests__/pages/isolasi-mandiri.test.tsx
  lib/layout/navigation-data.tsx
  pages/isolasi-mandiri.tsx
Labels: automerge

#496 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#497 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#499 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#492 fix: loading and empty state condition
  __tests__/pages/faq.test.tsx
  pages/faq.tsx
Labels: automerge

#501 feat(ui): homepage contributing widget
  components/home/__tests__/homepage-contributing.test.tsx
  components/home/homepage-contributing.tsx
  components/home/homepage-section.tsx
  components/home/homepage-start.tsx
  lib/home/contributing-links.tsx
  pages/index.tsx
Labels: automerge

#500 fix: move mobile navigation to the top
  components/home/__tests__/homepage-section.test.tsx
  components/layout/__tests__/global-header.test.tsx
  components/layout/__tests__/navigation.test.tsx
  components/layout/global-header.tsx
  components/layout/navigation.tsx
  components/ui/badge/__tests__/badge.test.tsx
  components/ui/badge/utils/types.ts
Labels: automerge

#502 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#505 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#503 Add a proper testing capability for the home page
  __tests__/pages/index.test.tsx
  __tests__/pages/provinces.test.tsx
  jest.config.js
  lib/__mocks__/home-page.ts
  lib/home-page.ts
  pages/index.tsx
Labels: automerge

#506 feat(ui): add WhatsApp hotline CTA
  components/home/__tests__/homepage-whatsapp-cta.test.tsx
  components/home/homepage-whatsapp-cta.tsx
  components/ui/__tests__/button.test.tsx
  components/ui/button/utils/helpers.ts
  components/ui/button/utils/types.ts
  components/ui/forms/__tests__/input-text.test.tsx
  components/ui/icons/index.ts
  components/ui/icons/whatsapp-icon.tsx
  components/ui/icons/whatsapp-logo.tsx
  pages/index.tsx
Labels: automerge

#508 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#513 fix: add `rel="nofollow"` attribute
  lib/htmr-transformers.tsx
Labels: automerge

#511 feat: latest news section implementation
  components/contact-details.tsx
  components/contact-list-item.tsx
  components/home/__tests__/homepage-latest-news.test.tsx
  components/home/homepage-latest-news.tsx
  lib/home/latest-news.ts
  lib/htmr-transformers.tsx
  pages/index.tsx
Labels: automerge

#518 refactor: move the sembako URL into a HOMEPAGE_START_CTA_URL constant
  components/home/__tests__/homepage-start.test.tsx
  components/home/homepage-start.tsx
  constants/index.ts
Labels: automerge

#512 feat: add WA hotline URL in config and update all links that use it
  _content/site-config.json
  components/home/homepage-whatsapp-cta.tsx
  components/layout/__tests__/navigation.test.tsx
  lib/__mocks__/site-config.ts
  lib/config.ts
  lib/layout/navigation-data.tsx
  lib/site-config.ts
  pages/_app.tsx
  pages/home-page.tsx
  pages/index.tsx
  pages/isolasi-mandiri.tsx
  public/admin/config.yml
Labels: automerge

#363 Design System Alert
  components/ui/__tests__/alert.test.tsx
  components/ui/__tests__/badge.test.tsx
  components/ui/alert/alert.tsx
  components/ui/alert/index.ts
  components/ui/alert/utils/__tests__/helpers.test.ts
  components/ui/alert/utils/helpers.ts
  components/ui/alert/utils/index.ts
  components/ui/alert/utils/types.ts
  components/ui/badge/utils/__tests__/helper.test.ts
  components/ui/badge/utils/helpers.ts
  components/ui/badge/utils/types.ts
  components/ui/types.ts
  jest.config.js
  pages/index.tsx
Labels: automerge

#520 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#437 chore(ui): add new welcome message to support website 2.0
  __tests__/pages/index.test.tsx
  _content/welcome-message.json
  _content/welcome-message.md
  components/home/homepage-welcome/__tests__/dialog.test.tsx
  components/home/homepage-welcome/__tests__/index.test.tsx
  components/home/homepage-welcome/dialog.tsx
  components/home/homepage-welcome/index.tsx
  env.d.ts
  jest.config.js
  lib/__mocks__/welcome-message.ts
  lib/hooks/use-intersection.ts
  lib/welcome-message.ts
  package.json
  pages/index.tsx
  public/admin/config.yml
  test/jest.client.js
  yarn.lock
Labels: automerge, need-perf-check

#523 fix(ui): fixed text size in latest news section
  components/home/homepage-latest-news.tsx
  lib/home/latest-news.ts
Labels: automerge

#529 Create Informasi Terbaru “wilayah-jakarta”
  _content/infomasi-terbaru/wilayah-jakarta.md
Labels: netlify-cms/pending_publish

#530 Create Informasi Terbaru “kementerian-kesehatan”
  _content/infomasi-terbaru/kementerian-kesehatan.md
Labels: netlify-cms/pending_publish

#531 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#533 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish
