Repository kawalcovid19/wargabantuwarga.com, pull requests merged in 2021-09, with the labels that each got.

#789 fix: minor fixes to homepage widgets
  components/home/homepage-supported-apps.tsx
  components/home/homepage-whatsapp-cta.tsx
  pages/index.tsx
Labels: automerge

#788 Feat Implement `fetch-database.ts`
  etc/fetchers/__mocks__/wbw-database.html
  etc/fetchers/__mocks__/wbw-database.json
  etc/fetchers/__tests__/fetch-database.test.ts
  etc/fetchers/fetch-database.ts
  etc/fetchers/fetch-wbw.ts
  jest.config.js
  package.json
  test/jest-common.js
  test/jest.server.js
  test/setup.server.js
  yarn.lock
Labels: need-perf-check, automerge

#793 test(e2e): write more e2e tests for provinces page and its subpages
  components/contact-list.tsx
  cypress/e2e/contacts/search.js
  cypress/support/commands.js
  package.json
  yarn.lock
Labels: need-perf-check
