Repository kawalcovid19/wargabantuwarga.com, pull requests merged in 2021-08, with the labels that each got.

#519 Move `Buka Peta` button under `Salin` button
  components/contact-details.tsx
Labels: automerge

#537 fix: use `h1` for page headers
  components/layout/page-header.tsx
Labels: automerge

#538 perf(seo): change Twitter Card handle
  pages/_app.tsx
Labels: automerge

#536 fix: use correct SEO title + improve a11y on Isolasi Mandiri page
  components/layout/stacked-link.tsx
  pages/isolasi-mandiri.tsx
Labels: automerge

#539 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#542 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#541 Fix internal links in Isolasi Mandiri page opens in a new tab
  components/layout/stacked-link.tsx
  lib/__tests__/string-utils.test.ts
  lib/string-utils.ts
Labels: automerge

#549 fix: change sembako URL back to `sembako.wargabantuwarga.com`
  components/home/__tests__/homepage-start.test.tsx
  constants/index.ts
Labels: automerge

#550 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#551 Update Informasi Terbaru “wilayah-jakarta”
  _content/informasi-terbaru/wilayah-jakarta.md
Labels: netlify-cms/pending_publish

#552 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#553 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#547 test: fetcher faqs
  etc/fetchers/__tests__/utils.test.ts
  etc/fetchers/fetch-faq-sheets.ts
  etc/fetchers/utils.ts
Labels: automerge, testing

#555 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#558 (ignore) Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#559 Create Informasi Terbaru “rumah-oksigen-gotong-royong-rogr”
  _content/informasi-terbaru/rumah-oksigen-gotong-royong-rogr.md
Labels: netlify-cms/pending_publish

#560 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#563 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#565 chore(kodiak): auto-merge deps updates from dependabot
  .kodiak.toml
Labels: automerge

#554 fix: extract query from contact and link props
  etc/fetchers/__tests__/utils.test.ts
  etc/fetchers/fetch-sheets.ts
  etc/fetchers/utils.ts
  lib/hooks/use-search.ts
  lib/string-utils.ts
  package.json
Labels: automerge

#515 Feat: Add Kontak Darurat Page
  __tests__/pages/kontak-darurat.test.tsx
  _content/kontak-darurat/emergency-contacts.json
  _content/kontak-darurat/oxygen-section.json
  _content/kontak-darurat/vaccine-section.json
  components/home/__tests__/homepage-start.test.tsx
  components/home/homepage-emergency-cta.tsx
  components/home/homepage-start.tsx
  components/kontak-darurat/__tests__/chatbot-section.test.tsx
  components/kontak-darurat/chatbot-section.tsx
  components/kontak-darurat/emergency-contact-card.tsx
  components/kontak-darurat/emergency-contact-content.tsx
  components/kontak-darurat/emergency-contact-section.tsx
  components/kontak-darurat/oxygen-section.tsx
  components/kontak-darurat/vaccine-section.tsx
  components/layout/stacked-link-disclosure.tsx
  components/stacked-link.tsx
  components/ui/icons/contact-icon.tsx
  components/ui/icons/index.ts
  components/ui/icons/phone-icon.tsx
  lib/content/__mocks__/builders/emergency-contacts.ts
  lib/content/__mocks__/builders/oxygen-section.ts
  lib/content/__mocks__/builders/vaccine-section.ts
  lib/content/__mocks__/emergency-contacts.ts
  lib/content/__mocks__/oxygen-section.ts
  lib/content/__mocks__/vaccine-section.ts
  lib/content/emergency-contacts.ts
  lib/content/oxygen-section.ts
  lib/content/vaccine-section.ts
  pages/kontak-darurat.tsx
  public/admin/config.yml
  public/images/bumn-1.png
  public/images/info-oxygen.png
  public/images/lentera-svarga.png
  public/images/logo_kemkes_2-1.png
Labels: automerge

#567 fix: revert back to mirror-box
  package.json
Labels: automerge

#566 feat: favicon wbw
  pages/_app.tsx
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-48x48.png
  public/favicon-72x72.png
  public/favicon-96x96.png
  public/favicon.ico
  public/logo-square-transparent-512x512.png
  public/logo-square-white-512x512.png
  public/manifest.json
  public/maskable/icon_x192.png
  public/maskable/icon_x384.png
  public/maskable/icon_x512.png
Labels: automerge

#575 feat: add Kontak Darurat page to navigation menu
  lib/layout/navigation-data.tsx
Labels: automerge

#574 refactor(layout): minor Page component fixes
  __tests__/pages/kontak-darurat.test.tsx
  components/kontak-darurat/emergency-contact-section.tsx
  components/layout/page-content.tsx
  components/layout/page-header.tsx
  pages/kontak-darurat.tsx
Labels: automerge

#577 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#562 fix: text overflow in link
  components/contact-details.tsx
Labels: automerge

#582 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#576 style: hide NProgress spinner
  __tests__/pages/_app.test.tsx
  jest.config.js
  package.json
  pages/_app.tsx
  test/jest-common.js
  yarn.lock
Labels: automerge

#579 fix: improve text color contrast
  components/home/__tests__/homepage-contributing.test.tsx
  components/home/__tests__/homepage-whatsapp-cta.test.tsx
  components/home/homepage-contributing.tsx
  components/home/homepage-latest-news.tsx
  components/home/homepage-whatsapp-cta.tsx
  components/ui/__tests__/button.test.tsx
  components/ui/button/__tests__/outline-anchor-button.test.tsx
Labels: need-perf-check, automerge

#571 feat(ui): open map button in list
  components/__tests__/contact-list-item.test.tsx
  components/contact-list-item.tsx
  lib/data/__mocks__/builders/provinces.ts
Labels: automerge

#578 change copywriting from Cek sekarang to Telusuri sekarang
  components/home/__tests__/homepage-start.test.tsx
  components/home/homepage-start.tsx
Labels: automerge

#596 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#601 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#602 docs: update README to add more requirements
  README.md
Labels: automerge

#604 feat: remove last updated alert from homepage
  __tests__/pages/index.test.tsx
  components/home/__tests__/homepage-content.test.tsx
  components/ui/__tests__/alert.test.tsx
  components/ui/alert/utils/__tests__/helpers.test.ts
  pages/index.tsx
  public/admin/config.yml
Labels: automerge

#619 Update About Page “about_page”
  _content/about/content.md
Labels: netlify-cms/pending_publish

#617 Update About Page “videos_about_page”
  _content/about/videos.json
Labels: netlify-cms/pending_publish

#618 Update About Page “collaborators_about_page”
  _content/about/collaborators.json
Labels: netlify-cms/pending_publish

#612 chore(security): add essential security headers
  netlify.toml
  next.config.js
Labels: automerge

#621 Update About Page “about_page”
  _content/about/content.md
Labels: netlify-cms/pending_publish

#622 Update About Page “videos_about_page”
  _content/about/videos.json
Labels: netlify-cms/pending_publish

#623 Update About Page “collaborators_about_page”
  _content/about/collaborators.json
Labels: netlify-cms/pending_publish

#625 style: minor tweaks to emergency contact layout
  components/kontak-darurat/__tests__/chatbot-section.test.tsx
  components/kontak-darurat/chatbot-section.tsx
  components/kontak-darurat/emergency-contact-section.tsx
Labels: automerge

#568 feat(donasi): Donasi Warga page + widget
  __tests__/pages/donasi.test.tsx
  _content/donasi.json
  components/donasi/donation-card.tsx
  components/home/__tests__/homepage-donation.test.tsx
  components/home/homepage-donation.tsx
  components/layout/internal-page-content.tsx
  lib/content/__mocks__/builders/donasi.ts
  lib/content/__mocks__/donasi.ts
  lib/content/donasi.ts
  pages/donasi.tsx
  pages/index.tsx
  public/admin/config.yml
  public/images/indonesia-pasti-bisa.png
Labels: automerge

#616 feat(page): New About page
  __tests__/pages/tentang-kami.test.tsx
  _content/about/content.md
  env.d.ts
  lib/content/about/__mocks__/content.ts
  lib/content/about/collaborators.ts
  lib/content/about/content.ts
  lib/content/about/videos.ts
  lib/layout/navigation-data.tsx
  pages/tentang-kami.tsx
  public/admin/config.yml
Labels: automerge

#614 feat: revert code coverage on home page
  __tests__/pages/index.test.tsx
  components/home/__tests__/homepage-content.test.tsx
  components/ui/__tests__/alert.test.tsx
Labels: automerge

#626 feat(image): using next/image
  __tests__/pages/tentang-kami.test.tsx
  constants/image.ts
  lib/__tests__/cloudinary-utils.test.ts
  lib/image/cloudinary-utils.ts
  pages/tentang-kami.tsx
Labels: automerge

#603 feat: added donasi on hamburger menu
  components/home/__tests__/homepage-start.test.tsx
  lib/home/homepage-menus.tsx
  lib/layout/navigation-data.tsx
Labels: automerge

#630 perf(security): added `Permissions-Policy` header
  netlify.toml
  next.config.js
Labels: automerge

#631 dialog: move margin on title to `div` parent
  components/home/homepage-welcome/dialog.tsx
Labels: automerge

#634 security: Add Content-Security-Policy
  netlify.toml
  next.config.js
Labels: automerge

#628 refactor: add internal page components + use it across the site
  __tests__/pages/404.test.tsx
  __tests__/pages/_error.test.tsx
  components/contact-list.tsx
  components/home/__tests__/homepage-start.test.tsx
  components/home/homepage-emergency-cta.tsx
  components/kontak-darurat/__tests__/chatbot-section.test.tsx
  components/kontak-darurat/chatbot-section.tsx
  components/kontak-darurat/emergency-contact-content.tsx
  components/kontak-darurat/emergency-contact-section.tsx
  components/layout/__tests__/global-header.test.tsx
  components/layout/global-header.tsx
  components/layout/internal-page-content.tsx
  components/layout/page.tsx
  components/layout/page/about-page-header.tsx
  components/layout/page/index.ts
  components/layout/page/internal-page-content.tsx
  components/layout/page/internal-page-header.tsx
  components/layout/page/internal-page-section.tsx
  components/layout/page/page-content.tsx
  components/layout/page/page-header.tsx
  components/layout/page/page.tsx
  components/ui/__tests__/feedback-section.test.tsx
  components/ui/alert/alert.tsx
  components/ui/alert/utils/helpers.ts
  components/ui/container.tsx
  components/ui/feedback-section.tsx
  pages/404.tsx
  pages/_error.tsx
  pages/donasi.tsx
  pages/faq.tsx
  pages/isolasi-mandiri.tsx
  pages/kontak-darurat.tsx
  pages/provinces/[provinceSlug]/[contactSlug].tsx
  pages/provinces/[provinceSlug]/index.tsx
  pages/provinces/index.tsx
  pages/tentang-kami.tsx
Labels: automerge

#540 Feat(ui): Implement Telemedicine Page
  __tests__/pages/telemedicine.test.tsx
  _content/telemedicine/telemedicine-contacts.json
  components/home/__tests__/homepage-telemedicine-cta.test.tsx
  components/home/homepage-telemedicine-cta.tsx
  components/telemedicine/telemedicine-contact-card.tsx
  components/telemedicine/telemedicine-contact-section.tsx
  lib/content/__mocks__/builders/telemedicine-contacts.ts
  lib/content/__mocks__/telemedicine-contacts.ts
  lib/content/telemedicine-contacts.ts
  lib/home/__tests__/get-contact-links.test.ts
  lib/home/get-contact-link.ts
  pages/index.tsx
  pages/telemedicine.tsx
Labels: need-perf-check, automerge

#606 feat: add 'ketersediaan' field to sheet
  components/__tests__/contact-details.test.tsx
  components/__tests__/contact-list-item.test.tsx
  components/contact-details.tsx
  components/contact-list-item.tsx
  etc/fetchers/__tests__/utils.test.ts
  etc/fetchers/fetch-sheets.ts
  etc/fetchers/utils.ts
  lib/data/__mocks__/builders/provinces.ts
  lib/data/provinces.ts
  package.json
  yarn.lock
Labels: automerge

#646 perf: cache static content to improve response time
  netlify.toml
Labels: need-perf-check, automerge

#647 fix: revert back to mirror box
  package.json
Labels: automerge

#653 Fix : allow some url to be allowed in `script-src` CSP
  netlify.toml
  next.config.js
Labels: automerge

#643 feat: add contribution icon in homepage
  components/home/__tests__/homepage-start.test.tsx
  components/ui/icons/contribution-icon.tsx
  components/ui/icons/index.ts
  lib/home/homepage-menus.tsx
Labels: automerge

#655 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#662 Update Education Page “education_contents”
  _content/educations.json
Labels: netlify-cms/pending_publish

#663 Update Education Page “education_contents”
  _content/educations.json
Labels: netlify-cms/pending_publish

#658 fix: seperate csp for admin page
  netlify.toml
Labels: automerge

#659 feat: handle external url icon
  components/home/__tests__/homepage-start.test.tsx
  components/home/homepage-menu.tsx
  lib/home/homepage-menus.tsx
Labels: automerge

#669 Update About Page “collaborators_about_page”
  _content/about/collaborators.json
Labels: netlify-cms/pending_publish

#671 Update Education Page “education_contents”
  _content/educations.json
Labels: netlify-cms/pending_publish

#636 feat: education page
  __tests__/pages/edukasi.test.tsx
  components/education/__tests__/education-link-section.test.tsx
  components/education/education-link-section.tsx
  components/home/homepage-telemedicine-cta.tsx
  components/layout/stacked-link-disclosure.tsx
  components/telemedicine/telemedicine-cta.tsx
  lib/content/educations.ts
  pages/edukasi.tsx
Labels: automerge

#676 fix: overflow alamat
  etc/fetchers/__tests__/utils.test.ts
  etc/fetchers/utils.ts
Labels: automerge

#678 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#681 style: adjust text size on cards
  components/donasi/donation-card.tsx
  components/kontak-darurat/emergency-contact-card.tsx
  components/telemedicine/telemedicine-contact-card.tsx
Labels: automerge

#667 fix: remove non-critical image from initial load
  components/home/__tests__/homepage-start.test.tsx
  components/home/__tests__/homepage-telemedicine-cta.test.tsx
  components/home/homepage-start.tsx
  components/telemedicine/telemedicine-cta.tsx
  pages/tentang-kami.tsx
Labels: need-perf-check, automerge

#682 feat: edukasi entry point
  components/home/__tests__/homepage-start.test.tsx
  lib/home/homepage-menus.tsx
  lib/layout/navigation-data.tsx
Labels: automerge

#690 Update Home Page “home_page”
  _content/home-page.md
Labels: netlify-cms/pending_publish

#692 docs: add securityheaders.com into Frequently Used Tools
  README.md
Labels: automerge

#695 test: fix unintended test skipping
  __tests__/pages/provinces/[provinceSlug]/[contactSlug].test.tsx
  jest.config.js
Labels: testing, automerge

#684 ci(lh-ci): add more urls to be tested
  .github/workflows/lighthouse-ci-for-pr.yml
  .github/workflows/lighthouse-ci-prod.yml
  README.md
Labels: need-perf-check, automerge

#700 Update Donasi Page “informasi_donasi”
  _content/donasi.json
Labels: netlify-cms/pending_publish

#694 feat: optimize font load using self-hosted variable fonts
  netlify.toml
  package.json
  pages/_app.tsx
  pages/_document.tsx
  public/fonts/inter-var-latin.woff2
  styles/globals.css
  yarn.lock
Labels: need-perf-check, automerge

#702 fix: color contrast ratio of Donasi Sekarang button
  components/donasi/donation-card.tsx
Labels: automerge

#699 ci: increase number of run
  .github/workflows/lighthouse-ci-for-pr.yml
  .github/workflows/lighthouse-ci-prod.yml
Labels: need-perf-check, automerge

#701 Update Kontak Darurat Page “emergency_contacts”
  _content/kontak-darurat/emergency-contacts.json
Labels: netlify-cms/pending_publish

#709 Update Donasi Page “informasi_donasi”
  _content/donasi.json
Labels: netlify-cms/pending_publish

#711 Update Home Page “official_supported_apps”
  _content/official_supported_apps.json
Labels: netlify-cms/pending_publish

#705 feat: pwa w next-pwa
  .gitignore
  next.config.js
  package.json
  wb.config.js
  yarn.lock
Labels: need-perf-check, automerge

#713 feat: add security.txt file
  public/.well-known/security.txt
Labels: automerge

#718 fix: try reverting `next-pwa` usage to fix #716
  next-env.d.ts
  next.config.js
Labels: automerge

#720 Revert "fix: try adding res.cloudinary.com to the content security po…
  netlify.toml
  next.config.js
Labels: automerge

#721 fix: add self-destroying service worker
  .gitignore
  public/service-worker.js
Labels: automerge

#661 fix: display filtered `kebutuhan` contacts count on province-list
  __tests__/pages/provinces/index.test.tsx
  components/__mocks__/builders/province-list.tsx
  components/province-list.tsx
  lib/data/helpers/provinces.ts
  pages/provinces/index.tsx
Labels: automerge

#726 fix: make NavigationMenuPopover scrollable and not override Navigation
  components/layout/__tests__/navigation.test.tsx
  components/layout/navigation-menu.tsx
  components/layout/navigation.tsx
Labels: automerge

#707 fix: revert whatsapp CTA button text color to white
  components/home/__tests__/homepage-whatsapp-cta.test.tsx
  components/home/homepage-whatsapp-cta.tsx
  components/kontak-darurat/__tests__/chatbot-section.test.tsx
  components/kontak-darurat/chatbot-section.tsx
  components/ui/button/ghosted-anchor-button.tsx
  components/ui/button/ghosted-button.tsx
Labels: automerge

#677 docs: explain forking mechanism to CONTRIBUTING
  CONTRIBUTING.md
  CONTRIBUTING_ID.md
Labels: automerge

#698 Refactor(ui): Replace Donasi Page Thumbnail Image
  components/donasi/donation-card.tsx
Labels: automerge

#729 docs: added reference to create commit message
  CONTRIBUTING.md
  CONTRIBUTING_ID.md
Labels: automerge

#727 Run Cypress tests in GitHub Actions
  .github/workflows/deploy.yml
  .github/workflows/lighthouse-ci-for-pr.yml
  .github/workflows/lighthouse-ci-prod.yml
  .github/workflows/test.yml
  .gitignore
  cypress.json
  cypress/e2e/provinces/search.js
  cypress/fixtures/example.json
  cypress/integration/provinces/search.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: need-perf-check, automerge

#735 fix: add `analytics.google.com` to `connect-src` CSP rule
  netlify.toml
  next.config.js
Labels: automerge

#737 fix: add CSP header for analytics in the correct paths
  netlify.toml
Labels: automerge

#738 fix: tweak logos section in the about us page
  next-env.d.ts
  pages/tentang-kami.tsx
Labels: automerge

#739 fix(security): add CSP rules for `stats.g.doubleclick.net`
  netlify.toml
  next.config.js
Labels: automerge

#728 test: replace toMatchInlineSnapshot with meaningful assertions
  components/__tests__/report-button.test.tsx
  components/__tests__/search-filter.test.tsx
  components/__tests__/search-form.test.tsx
  components/home/__tests__/homepage-contributing.test.tsx
  components/home/__tests__/homepage-header.test.tsx
  components/home/__tests__/homepage-start.test.tsx
  components/home/__tests__/homepage-telemedicine-cta.test.tsx
  components/home/__tests__/homepage-whatsapp-cta.test.tsx
  components/kontak-darurat/__tests__/chatbot-section.test.tsx
  components/layout/__tests__/global-header.test.tsx
  components/layout/__tests__/navigation.test.tsx
  components/ui/__tests__/alert.test.tsx
  components/ui/__tests__/feedback-section.test.tsx
  components/ui/__tests__/responsive-img.test.tsx
Labels: automerge

#725 feat: add JsonLd
  components/json-ld/builder.tsx
  components/json-ld/webpage.tsx
  components/json-ld/website.tsx
  components/layout/page/about-page-header.tsx
  components/layout/page/internal-page-header.tsx
  components/layout/page/page-header.tsx
  lib/__tests__/jsonld-generator.test.ts
  lib/jsonld-generator.ts
  pages/faq.tsx
  pages/index.tsx
  pages/isolasi-mandiri.tsx
  pages/provinces/[provinceSlug]/[contactSlug].tsx
  pages/provinces/[provinceSlug]/index.tsx
  pages/provinces/index.tsx
Labels: need-perf-check, automerge

#745 Update About Page “collaborators_about_page”
  _content/about/collaborators.json
Labels: netlify-cms/pending_publish

#746 Update About Page “videos_about_page”
  _content/about/videos.json
Labels: netlify-cms/pending_publish

#747 Update About Page “videos_about_page”
  _content/about/videos.json
Labels: netlify-cms/pending_publish

#741 refactor: update GitHub action for not running on forked repo
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .github/workflows/lighthouse-ci-prod.yml
  .github/workflows/test.yml
Labels: automerge

#706 feat(CMS): supported apps by kemnkes
  _content/officially_supported_apps.json
  public/admin/config.yml
Labels: automerge

#742 docs: added information related to github action
  CONTRIBUTING.md
  CONTRIBUTING_ID.md
Labels: automerge

#753 docs: add Cypress logo as supporter
  README.md
Labels: automerge

#752 chore: migrate tailwind config to `tailwind-preset-wbw`
  package.json
  tailwind.config.js
  yarn.lock
Labels: automerge

#734 fix: remove warning tentang kami on test
  pages/tentang-kami.tsx
Labels: need-perf-check, automerge

#755 fix: changed card button colours to `brand`
  components/kontak-darurat/emergency-contact-card.tsx
Labels: automerge

#733 feat: added supported apps on homepage
  _content/home-page.md
  components/home/__tests__/homepage-supported-apps.test.tsx
  components/home/homepage-supported-apps.tsx
  lib/content/officially-supported-apps.ts
  pages/index.tsx
Labels: need-perf-check, automerge

#756 docs: add Netlify logo to our supporters list
  README.md
Labels: automerge

#750 docs(dx): explain our use of Conventional Commits in CONTRIBUTING.md
  CONTRIBUTING.md
  CONTRIBUTING_ID.md
Labels: automerge

#759 Add Conditional Deployment Schedule Based on Hour
  .github/workflows/deploy.yml
Labels: automerge

#765 fix: replace rounded-md with rounded-t-md
  components/donasi/donation-card.tsx
Labels: automerge

#776 docs(template): remove default assignees from issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: automerge

#762 feat: pwa registration
  .gitignore
  netlify.toml
  next.config.js
  package.json
  public/service-worker.js
  wb.config.js
  yarn.lock
Labels: need-perf-check, automerge

#781 feat: add Telekonseling Page to CMS & update Homepage
  components/home/__tests__/homepage-supported-apps.test.tsx
  components/home/homepage-supported-apps.tsx
  pages/index.tsx
  public/admin/config.yml
Labels: automerge
